version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/tidwall/gjson
    versions:
    - 1.6.7
    - 1.7.1
    - 1.7.3
    - 1.7.4
  - dependency-name: github.com/ory/dockertest/v3
    versions:
    - 3.6.3
